### ISSUE TITLE
Ctrl-S has no effect; must use File|Save

### ISSUE THREAD

**Issue by sjsepan3** [dineug/textflow#1]
**Desc**:
When saving changes, using Ctrl-S does nothing. Using File|Save works. Note: have not run Extension Bisect yet; will try that next.

**Codium**:
Version: 1.94.0
Release: 24281
Commit: e3ecc7b1f165b02bbce073afbe9ab016559e91cb
Date: 2024-10-07T16:22:10.210Z
Electron: 30.5.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-122-generic

**System Info**:
System:
  Kernel: 5.15.0-122-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Dell product: OptiPlex 5040 v: N/A serial: <superuser required> Chassis:
    type: 3 serial: <superuser required>
  Mobo: Dell model: 0R790T v: A00 serial: <superuser required> UEFI-[Legacy]: Dell v: 1.2.7
    date: 01/15/2016
Battery:
  Device-1: hidpp_battery_0 model: Logitech M570 serial: <filter> charge: 40% rechargeable: yes
    status: Discharging
CPU:
  Info: quad core model: Intel Core i5-6500 bits: 64 type: MCP smt: <unsupported> arch: Skylake-S
    rev: 3 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 1862 high: 2000 min/max: 800/3600 cores: 1: 2000 2: 1727 3: 1904 4: 1818
    bogomips: 25599
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 535.171.04 pcie: speed: 8 GT/s
    lanes: 4 ports: active: none off: HDMI-A-1 empty: DVI-D-1 bus-ID: 01:00.0 chip-ID: 10de:1d01
    class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x2160 s-dpi: 162 s-size: 602x341mm (23.7x13.4") s-diag: 692mm (27.2")
  Monitor-1: HDMI-0 res: 3840x2160 hz: 60 dpi: 163 size: 600x340mm (23.6x13.4")
    diag: 690mm (27.2")
  OpenGL: renderer: NVIDIA GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 535.171.04
    direct render: Yes
Audio:
  Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3 chip-ID: 8086:a170 class-ID: 0403
  Device-2: NVIDIA GP108 High Definition Audio driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 4 bus-ID: 01:00.1 chip-ID: 10de:0fb8 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-122-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I219-V vendor: Dell driver: e1000e v: kernel port: N/A bus-ID: 00:1f.6
    chip-ID: 8086:15b8 class-ID: 0200
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: virbr0 state: down mac: <filter>
Drives:
  Local Storage: total: 1.14 TiB used: 1.6 TiB (139.7%)
  ID-1: /dev/sda vendor: SanDisk model: SD8SBAT-256G-1006 size: 238.47 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: 1006 scheme: GPT
  ID-2: /dev/sdb vendor: Western Digital model: WDS100T2B0A-00SM50 size: 931.51 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: 20WD scheme: MBR
Partition:
  ID-1: / size: 233.62 GiB used: 120.64 GiB (51.6%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 47.2 MiB used: 6 MiB (12.8%) fs: vfat dev: /dev/sda2
  ID-3: /home size: 915.82 GiB used: 757.16 GiB (82.7%) fs: ext4 dev: /dev/sdb1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 45.8 MiB (2.2%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 16 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-5:2 info: 816820090226 type: Mass Storage driver: usb-storage interfaces: 1
    rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 3207:0300 class-ID: 0806 serial: <filter>
  Device-2: 1-9:3 info: Logitech Unifying Receiver type: Keyboard,Mouse,HID
    driver: logitech-djreceiver,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s power: 98mA
    chip-ID: 046d:c52b class-ID: 0300
  Hub-2: 2-0:1 info: Super-speed hub ports: 10 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 29.8 C pch: 59.0 C mobo: 27.8 C gpu: nvidia temp: 38 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 86%
Repos:
  Packages: note: see --pkg apt: 4288
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/gambas-team-gambas3-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/gambas-team-gambas3-jammy.gpg] https: //ppa.launchpadcontent.net/gambas-team/gambas3/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/jonaski-strawberry-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/jonaski-strawberry-jammy.gpg] https: //ppa.launchpadcontent.net/jonaski/strawberry/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/krupkat-code-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/krupkat-code-jammy.gpg] https: //ppa.launchpadcontent.net/krupkat/code/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/lightzone-team-lightzone-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/lightzone-team-lightzone-jammy.gpg] https: //ppa.launchpadcontent.net/lightzone-team/lightzone/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/nala-sources.list
    1: deb http: //mirrors.advancedhosters.com/ubuntu/ jammy main restricted universe multiverse
    2: deb http: //mirror.cs.jmu.edu/pub/ubuntu/ jammy main restricted universe multiverse
    3: deb http: //mirror.us-ny2.kamatera.com/ubuntu/ jammy main restricted universe multiverse
    4: deb https: //mirror.umd.edu/ubuntu/ jammy main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //fastly.linuxmint.io virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/teejee2008-foss-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/teejee2008-foss-jammy.gpg] https: //ppa.launchpadcontent.net/teejee2008/foss/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/vivaldi.list
    1: deb [arch=amd64] https: //repo.vivaldi.com/stable/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/vscodium.list
    1: deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https: //download.vscodium.com/debs vscodium main
  Active apt repos in: /etc/apt/sources.list.d/warpdotdev.list
    1: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/warpdotdev.gpg] https: //releases.warp.dev/linux/deb stable main
Info:
  Processes: 294 Uptime: 4h 13m wakeups: 12 Memory: 15.54 GiB used: 4.64 GiB (29.9%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 clang: 14.0.0-1ubuntu1.1
  Client: Unknown python client inxi: 3.3.13

**Comment by sjsepan3** [comment]
Update: I ran bisect, but pressing 'Preview on GitHub' button has no effect. I reproduce my comments here...

"dineup/textflow
Running Bisect seems to produce indeterminate results from my perspective. I say this because while the issue was reproducible with the extension enabled, I could not see the .txf.json content while it was disabled. Pressing Ctrl-S still did nothing, but I cannot say whether that was because the bug was present or the content was not present. I include this test for completeness' sake."

**Comment by dineug** [comment]
Thank you for letting me know!
I made changes in version 0.1.5

**Comment by sjsepan3** [comment]
> Thank you for letting me know! I made changes in version 0.1.5

@dineug Version 0.1.5 fixes the issue -- Thank You!
