### ISSUE TITLE
H3 headers are smaller than usual text

### ISSUE THREAD

**Issue by alexeyshesh** [dineug/textflow#2]
Hi! I found your extension today and it is awesome

Got some strange behaviour – H3 headers are smaller than normal text:

<img width="810" alt="Screenshot 2024-10-30 at 15 21 50" src="https://github.com/user-attachments/assets/a4de7b65-f657-483a-a781-aabc36f2aef0">

MacOS, extension v. 0.1.7

**Comment by dineug** [comment]
I made changes in version 0.1.8.

**Comment by alexeyshesh** [comment]
Thanks! Will wait for the new version on VS Code Marketplace
